### ISSUE TITLE
ERROR: while preparing training data

### ISSUE THREAD

**Issue by sciai-ai** [as-ideas/TransformerTTS#113]
Hi,

1. I ran the command 

`python create_training_data.py --config config/training_config.yaml`

It loaded all the wave files and produced the pitch, .npy files. However I am getting the error below:

![image](https://user-images.githubusercontent.com/52277510/121469418-06009400-c9ef-11eb-844d-d539670e0e1a.png)

2. I want to have a special symbol for the breathing at the beginning of wav files, so I set the flag to true in the config file. How does it handle the case to trim silence at the front when the breathing is True?

**Comment by sciai-ai** [comment]
solved

**Comment by cfrancesco** [comment]
Hi
Would you mind sharing what the problem was?

Breathing token and silence trimming are independent. You can add the breathing token with no breathing in the data, won't break anything, just wouldn't work as intended.
