### ISSUE TITLE
the missing of HiFiGAN model.pt

### ISSUE THREAD

**Issue by chikiuso** [as-ideas/TransformerTTS#130]
Good morning, I run through all training process with my own dataset, I run the predict with HiFiGAN vocoder with this setting :

- parser.add_argument('--voc', dest='vocoder', default='hifigan')

But it turns out to be this message : 

- FileNotFoundError: [Errno 2] No such file or directory: 'vocoding/hifigan/en/model.pt'

May I ask where could I locate the hifigan model.pt? thanks!

Best wishes,
Jack

**Comment by alexvwegen** [comment]
Did you also trained a HiFiGAN model on your own data or just the TTS?
If you want to use a pretrained HiFiGAN model, I'd have a look at the HiFiGAN repository => [https://github.com/jik876/hifi-gan](url) There are some pretrained models linked that you can use. 
However from my experience, it's best to train HiFiGAN on your data as well for the best sounding results.

**Comment by chikiuso** [comment]
thanks for your help :D
