### ISSUE TITLE
Audio Not Generating At All

### ISSUE THREAD

**Issue by rish-16** [as-ideas/TransformerTTS#14]
Hey!

Was playing around with the notebook and ran the cells one by one. When I tried listening to the audio generated by the model using the IPython display function, the audio was a 4 second long stream of soft `booming` noises and didn't sound anything like the input sentence.

Would love to know how to proceed.

Cheers :D

**Comment by cfrancesco** [comment]
Hi,
I see, there is an issue with the autoregressive model loading. 
Thanks for pointing it out.

**Comment by rish-16** [comment]
This was, unfortunately, with the `forward` model :(

I already bypassed the `f_max` issue by setting it to `None` using the hack you mentioned above. But I got another error that persisted till I changed `f_max` to an actual integer number like 50 or 100 from `None`

Also, would love to have some sort of function built into `utils/audio.py` that converts the Griffin Lim out from Librosa in `reconstruct_waveform(..)` into a savable `.wav` file that can be played using the audio player. I tried using Librosa's `output.write_wav` function but it was corrupted mainly because the model's output was of poor quality.

**Comment by cfrancesco** [comment]
Oh ok, is it still not working? Are we talking about the colab notebook?
When I run it everything seems fine. 
could you try to factory reset the runtime on colab? top bar -> runtime -> restart runtime

**Comment by rish-16** [comment]
Sure, I'll try that.

And I tried locally running it as well and ran into a similar problem.

**Comment by padmalcom** [comment]
Since this ticket is closed I guess you solved the issue? Can you tell us how?
