### ISSUE TITLE
Unequal input array dimensions in create_dataset.py

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#22]
I'm currently trying to execute the create_dataset script. It fails with an invalid array size in line 65 of create_dataset.py.

`ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3515 and the array at index 1 has size 3514`

I checked the metadata.csv and the wav files in the folder waves. Numbers are the same. The error occurs even with a different dataset.

Do you have a clue where this error comes from?

**Comment by ConProgramming** [comment]
Had the same error as you, my `metadata.csv` had a line where the transcription was empty... do a search in your editor for the delimiter then a new line. Remove the line with an empty transcription and it'll work.

**Comment by padmalcom** [comment]
It was the following entry in the metadata.csv:

`menschenhasser_04_f000032|–, und eben da hat er so mancherlei durchblicken lassen.|-, und eben da hat er so mancherlei durchblicken lassen.`

Removing the leading `-,` made it work.

**Comment by cfrancesco** [comment]
So it happens with both empty lines and leading `,` ?

@padmalcom do you know why the error arises? Seems like a phonemizer issue

**Comment by padmalcom** [comment]
I can't confirm the behavior for empty lines but with those starting with `-,`. I'm sure it is an issue with phoenemizer, but it can easily be avoided so I do not really see an issue here. Maybe implement a sanitizer step before creating the training data?

**Comment by cfrancesco** [comment]
Ok thanks. Yeah a cleaner is already in place, I'll try to understand the principle behind this and add it to it. (it also breaks when there is two punctuation and a space in between, like ", ,")
