### ISSUE TITLE
ModuleNotFoundError: No module named 'numba.decorators'

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#28]
When installing the requirements.txt the error `ModuleNotFoundError: No module named 'numba.decorators'` appears. Uninstalling `numba==0.50.0` and installing `numba==0.49.1` solves the issue.

**Comment by cfrancesco** [comment]
Is this with a fresh environment? Could you post your system specs?

**Comment by padmalcom** [comment]
Yes, with an empty environment. The error occurs with python 3.6 and 3.7. I'm using anaconda on a 64bit CentOS 7.

**Comment by cfrancesco** [comment]
Apparently it's a librosa issue. It was reported here too
https://github.com/librosa/librosa/issues/1160
https://github.com/deezer/spleeter/issues/419#issuecomment-643820904
Could you try installing librosa==0.7.1?
I'll probably fix the librosa version for now.

**Comment by manmay-nakhashi** [comment]
try this 
pip install numba==0.43.0
pip install llvmlite==0.32.1

**Comment by padmalcom** [comment]
As mentioned in the first post uninstalling numba 0.50.0 and installing 0.49.1 solves the issue. Just wanted you to know that this error occurs. I could confirm it on my Windows 7 as well (again Anaconda and Python 3.6 and 3.7).

**Comment by padmalcom** [comment]
This one can be closed from my perspective. Fix is to add `numba==0.49.1` to `requirements.txt`.
