### ISSUE TITLE
How to listen to the audio files created by create_dataset.py?

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#32]
When listening to the target files in tensorboard, I recognized that the audio quality of the target wavs is pretty bad. Where do these target audio files come from? I could not find them anywhere in the training data or the logs folder.

**Comment by padmalcom** [comment]
I now convert the sample rate using ffmpeg before training and audio quality gets better so this one can be closed.

**Comment by Bardo-Konrad** [comment]
Kannst du auf https://github.com/as-ideas/TransformerTTS/issues/51 antworten?

**Comment by padmalcom** [comment]
To be honest: I can't. You neither said what your exact issue is nor what you changed in the example code.

**Comment by cfrancesco** [comment]
> I now convert the sample rate using ffmpeg before training and audio quality gets better so this one can be closed.

Hi, I missed this issue, sorry. Could you explain what you did there? Preprocessing with librosa should already resample the wavs appropriately.
