### ISSUE TITLE
Error converting audio using melgan

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#33]
Hi, I try to use melgan to produce wav files but I get a `TransformerTTS/utils/audio.py:96: RuntimeWarning: overflow encountered in exp`.

The colab notebook is not clear on how to do the conversion, since the last lines are:
```
if torch.cuda.is_available():
    vocoder = vocoder.cuda()
    mel = mel.cuda()

with torch.no_grad():
    audio = vocoder.inference(mel)
```

I'm expecting to do sth like:

```
wav = audio.reconstruct_waveform(audio.cpu().numpy().T)
librosa.output.write_wav('melgan1.wav', wav, 22050)

```

But it gives me the error in audio.py. Can you help me out?

**Comment by pizzabug** [comment]
Hi, @padmalcom; while it's not using librosa as you provided, I've been using scipy to do the conversion from the melgan result, as per the [inference implementation](https://github.com/seungwonpark/melgan/blob/master/inference.py) in the [melgan repo](https://github.com/seungwonpark/melgan/). I used the `write` method from `scipy.io.wavfile` in such a manner;

```py
if torch.cuda.is_available():
    vocoder = vocoder.cuda()
    mel = mel.cuda()

with torch.no_grad():
    audio = vocoder.inference(mel)
    audio_w = audio_w.cpu().detach().numpy() #Detach from GPU

out_path = ('path/to/result.wav')
scipy.io.wavfile.write(out_path, 22050, audio_w)
```

**Comment by padmalcom** [comment]
@pizzabug Thanks, this works pretty well :)
