### ISSUE TITLE
Missing words in audio, improper pauses

### ISSUE THREAD

**Issue by aayushkubb** [as-ideas/TransformerTTS#35]
Hey,

I have been trying custom training the models using custom dataset(non-english) ensuring the language is supported by the phonemizer https://github.com/espeak-ng/espeak-ng .

I am using non-english characters as the training set, the phonemes generated are long due to richness in the language, the data set is well cleaned and seems okay for the task.

However, TTS-Autoregressive training is not coming as expected. At times synthesis misses out on a few words, or there are improper pauses after commas and full stops.

The Melgan is training very well and has converged properly. However, for TTS, the losses are stagnant and doesn't seem to improve further but still getting the issue.

Can anyone help in identifying on what could be going wrong here? Is it a dataset issue or a phoneme level issue?
What to look at and what not? Any pointer would be helpful.

PS: I have already replicated results on English on a custom dataset which are very good.

Thanks

**Comment by cfrancesco** [comment]
Yes, the autoregressive model is unstable and hard to train. It should only be used to train the forward model.
Pauses are hard to predict if there is a lot of variations and skipping words is a known issue.

Are the decoder heads aligning properly? (check this from tensorboard)

**Comment by OthmanEmpire** [comment]
I would like to use the code to generate some audio samples as voice-overs for some tutorials I'm creating. I've been testing the code out, and as @aayushkubb mentioned, there are missing words and other odd behaviour.

My machine learning background is fairly lacking so excuse my terminology and lack of understanding, however, I would like to use the 'Autoregressive + MelGAN' colab since it sounds best. Would it be possible to use the Autoregressive model to only train the forward model (MelGAN), and then feed a custom sentence to MelGAN for it vocalize?

In terms of code, that doesn't seem so possible. The relevant bits after dissecting it a bit are the sections below. I would like to feed the `torch.tensor()` function a custom sentence like the Autoregressive portion and not the output audio file of the Autoregressive. Does this even make sense in the context of this machine learning algorithm?

```
# Synthesize text
sentence = 'Scientists at the CERN laboratory, say that they have discovered a new particle.'
out = model.predict(sentence)
```

```
sys.path.append(MelGAN_path)
import torch
import numpy as np

vocoder = torch.hub.load('seungwonpark/melgan', 'melgan')
vocoder.eval()

mel = torch.tensor(out['mel'].numpy().T[np.newaxis,:,:])
```

**Comment by cfrancesco** [comment]
> I would like to use the code to generate some audio samples as voice-overs for some tutorials I'm creating. I've been testing the code out, and as @aayushkubb mentioned, there are missing words and other odd behaviour. I do understand though that there are some technical limitations mentioned.
> 
> My machine learning background is fairly lacking so excuse my terminology and lack of understanding, however, I would like to use the 'Autoregressive + MelGAN' colab since it sounds best. Would it be possible to use the Autoregressive model to only train the forward model (MelGAN), and then feed a custom sentence to MelGAN for it vocalize?
> 
> In terms of code, that doesn't seem so possible. The relevant bits after dissecting it a bit are the sections below. I would like to feed the `torch.tensor()` function a custom sentence like the Autoregressive portion and not the output audio file of the Autoregressive. Does this even make sense in the context of this machine learning algorithm?
> 
> ```
> # Synthesize text
> sentence = 'Scientists at the CERN laboratory, say that they have discovered a new particle.'
> out = model.predict(sentence)
> ```
> 
> ```
> sys.path.append(MelGAN_path)
> import torch
> import numpy as np
> 
> vocoder = torch.hub.load('seungwonpark/melgan', 'melgan')
> vocoder.eval()
> 
> mel = torch.tensor(out['mel'].numpy().T[np.newaxis,:,:])
> ```

I'm not sure about the last portion of you message, but I would recommend you use the Forward model for TTS (for highest stavbility, autoregressive is just very unstable) and convert with WaverRNN for the highest quality.

The thing you feed to the vocoder (either MelGAN or WaverRNN) are spectrogram predictions from TTS models, so neither text nor audio.

If you have more questions please open a new issue.
