### ISSUE TITLE
How to change the phonemizer?

### ISSUE THREAD

**Issue by juunnn** [as-ideas/TransformerTTS#39]
Hi, I tried this code it's really good and fast. But I have problem with the phonemizer. Since I dont use english for my model the phonemizer is a little bit off. there is some word that have wrong pronounciation, is there any way that I change the phonemizer or turn of that option? 
Thanks you for your feedback.

**Comment by cfrancesco** [comment]
In the configuration files there is a language option. Did you try to change that? 
I choose not to allow character embedding vs phonemes embedding for now.

**Comment by juunnn** [comment]
Thank you for your feedback. I try to trace the code and found the exception raise from [here](https://github.com/as-ideas/TransformerTTS/blame/master/preprocessing/text/__init__.py). it only allows german and English or German cleaner. When I comment that line, the code works fine. 
Once again, thank you.
