### ISSUE TITLE
Problem with sentence cleaners/phonemizer Pipeline

### ISSUE THREAD

**Issue by Yannecc** [as-ideas/TransformerTTS#40]
when using the default cleaner for LibriTTS, I came across a strange behavior of the preprocessing pipeline.

I decided to replace '...' with a comma in the cleaner, to avoid buggy punctuation (though i realize it might be what causes the subsequent problem) 

This leads to the presence of  the substring ' , ?'  in the end of sentence n°4 of the batch shown below. (Initially, it was ' . . . ?')

When processed with the phonemizer, it appears the said substring (comma-question mark) affects the processing, which goes goes very wrong: the batch goes from length 10 to length 9 by fusing sentence 4 and 5 in a single output, then n°6 gets cut, and then the question marks from later sentences end up in the wrong sentences and everything afterwards is shifted and does not behave as normal.

This is the batch I feed in: (I reduced batch size in order to localize where it happened)
(Pay attention to the number before sentences)

0.'What risks would you run in a job like that? Ned Land said. Swallowing a few gulps of salt water? ',
1.'Whatever you say, Ned. Then, trying to imitate Captain Nemos carefree tone, I asked, By the way, gallant Ned, are you afraid of sharks? ',
2.'Me? the Canadian replied ',
3.'Im a professional harpooner! Its my job to make a mockery of them! ',
4.'So its an issue of , ? ', 
5.'In the water? ',
6.'You see, sir, these sharks are badly designed ',
7.'They have to roll their bellies over to snap you up, and in the meantime  ',
8.'What are your feelings about these man eaters? ',
9.'Im afraid I must be frank with master ',

output:

0.'wɒt ɹɪsks wʊd juː ɹʌn ɪn ɐ dʒɒb laɪk ðat? nɛd land sɛd. swɒləʊɪŋ ɐ fjuː ɡʌlps ɒv sɒlt wɔːtə? ',
1.'wɒtɛvə juː seɪ, nɛd. ðɛn, tɹaɪɪŋ tʊ ɪmɪteɪt kaptɪn niːməʊz keəfɹiː təʊn, aɪ askt, baɪ ðə weɪ, ɡalənt nɛd, ɑː juː ɐfɹeɪd ɒv ʃɑːks? ',
2.'miː? ðə kɐneɪdiən ɹɪplaɪd',
3.'ɪm ɐ pɹəfɛʃənəl hɑːpuːnə! ɪts maɪ dʒɒb tə meɪk ɐ mɒkəɹi ɒv ðɛm! ',
4.'səʊ ɪts ɐn ɪʃuː ɒv , ɪnðə wɔːtə? ',   **(n° 4 and 5 are "glued together")**
5.'juː siː? ',                                         **(start of n°6 with unexpected question mark)**
6.'sɜː, ðiːz ʃɑːks ɑː badli dɪzaɪnd, ðeɪ hav tə ɹəʊl ðeə bɛlɪz əʊvə tə snap juː ʌp', **(n°6 and start of n° 7 without the end)**
7.'and ɪnðə miːntaɪm, wɒt ɑː jɔː fiːlɪŋz ɐbaʊt ðiːz man iːtəz', **(end of n°7, plus n°8)**
8.'ɪm ɐfɹeɪd aɪ mʌst biː fɹaŋk wɪð mastə? ' **(n°9 with unexpected question mark)**

Sorry for the clumsy report, it is quite hard to explain what happens. It is the only sentence from "train-clean-100" which leads to this problem. It is also the only one containing the substring ' . . . ?'

Maybe replacing dot-dot-dot with comma was not the best workaround, but I think there is something which goes wrong beyond that here...

**Comment by cfrancesco** [comment]
Hi,
there are some substrings which break the phonemizer in various ways unfortunately. Many double punctiations with a space in between do so. Try to remove the white space. This is probably best reported on the phonemizer repo.

**Comment by Yannecc** [comment]
Oh yes sorry I didn't notice the phonemizer was not made by you.
For the record I also noticed that the word "Dieu" (capitalized or not) always yields an error when passed to the english phonemizer.
The error is "Nonetype object has no attribute warning".
I haven't found any other word leading to this, even other french words like miséricodieux or vieux

**Comment by cfrancesco** [comment]
That actually is an issue with multi threading within the phonemizer. Most likely, it's trying to switch language on that word, which would throw a warning, but due to a bug if you're using multiple jobs it will break. Change njobs to 1 to solve. (although on their repo it waas recently fixed, not in the package afaik)
