### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bheshaj96** [as-ideas/TransformerTTS#47]
Hey, thanks so much for the code
I don't have any contact to ask you so thought to ask here. Extremely sorry for this.
I am new to TTS and want to implement latest multispeaker TTS system paper [here](https://arxiv.org/abs/2006.04664) 

The speaker module here is passing outputs to encoder and pre decoder. My issue is since my seq Len will be different for encoder and pre decoder output, how do I concat the speaker output in the two in tensorflow.
More specifically since enc output will be (batch, inp_seq_len, d) and predecoder output (batch, out_seq_len, d) how to concat different speaker ids on each sequency parallelly?
Currently I am thinking to create two speaker inps of size (batch, inp_seq,speaker Id ) and pass through speaker module to get shape which can be concatenated with enc output with speaker module training set to true. Then create another speaker input which is compatible with out seq Len and pass through speaker module to get output compatible with pre decoder with training set to false.
I don't have anyone else to ask hence asking you.
Thanks

**Comment by cfrancesco** [comment]
Hi,
this is the right place where to ask, don't be sorry!
I would recommend to concatenate the speaker id to each timestep, so it does not depend on the sequence length. For instance if in encoder input you have a shape of (batch_size, inp_seq, d) it will become (batch_size, inp_seq, d + speaker_embedding_dimension).
Not sure if you have to concatenate again in the decoder input.

Hope this helps.
