### ISSUE TITLE
with_stress is missing in autoforward config file

### ISSUE THREAD

**Issue by padmalcom** [as-ideas/TransformerTTS#48]
Hi, as the title says: `with_stress` is missing in autoforward config file

**Comment by Bardo-Konrad** [comment]
put `with_stress: true` there

**Comment by cfrancesco** [comment]
I mistakenly added 'use_stress' instead. Fixed. I might move away from yaml configs.

**Comment by apthagowda97** [comment]
The issue is still present in the colab example.
