### ISSUE TITLE
Possible to fine-tune on new dataset?

### ISSUE THREAD

**Issue by napalm00** [as-ideas/TransformerTTS#49]
Is it possible to fine-tune the pretrained LJSpeech model on a new dataset (English, but also potentially others)?
If so, would we have to resume training on both the autoregressive model and the forward model or just the forward model?

**Comment by cfrancesco** [comment]
Do you mean if there is a specific feature for this? In this case not, but for can for sure load the model weights and have it train on new data. 
Based on our experiments this works well sometimes (if not cross-language)

**Comment by napalm00** [comment]
I meant training on new data using the released model weights yes, thank you for confirming!

**Comment by giymen** [comment]
Hi @napalm00, I also try to train the model starting from pretrained weights. I thought that I can use same session name as pretrained model, and by increasing max_steps to bigger numbers I can do it.  
Did you manage to do it, and how?

**Comment by napalm00** [comment]
Hey @giymen , I'm still experimenting and I'm doing the same as you are, same session name + increasing max_steps (and setting the data and log folders accordingly ofc), however I wasn't able to get any good results yet; I wish there was a colab that would show how to do the training.
So far I've only managed to get very robotic voices after ~20hrs of training on a 8hrs length dataset (which was tested on Tacotron2 and works fine) using the weights from commit 1c1cb03 (MelGAN), I'm experimenting with the weights from commit d9ccee6 (WaveRNN) but I still get very robotic voices.

**Comment by napalm00** [comment]
@cfrancesco mentioned he had good results training on new data in his experiments, it would be interesting to know the weights used, the duration of the new dataset and how long it took to train.
