### ISSUE TITLE
How do you use TransformerTTS?

### ISSUE THREAD

**Issue by Bardo-Konrad** [as-ideas/TransformerTTS#61]
My intended purpose is to have new voices for book to audiobook conversions for private consumption.

How do you use TransformerTTS?

**Comment by cfrancesco** [comment]
README.md

**Comment by Bardo-Konrad** [comment]
Thanks ;)
My phrasing was wrong. I am curious about what you use it for, ie the task you want to accomplish with it.

**Comment by cfrancesco** [comment]
hahaha ok, I misunderstood the question.
We have a minimal usecase for now where we convert news articles into audio, so it can be listened to "podcast style" by the users.

**Comment by Bardo-Konrad** [comment]
Can you share some links to your "podcasts"?

**Comment by cfrancesco** [comment]
Only German unfortunately:
https://www.welt.de/wirtschaft/article209346567/Globalisierung-So-abhaengig-sind-wir-wirklich-von-China.html
Here we used one of our first Tacotron models.

**Comment by Bardo-Konrad** [comment]
Ich bin Deutscher. Danke.

**Comment by cfrancesco** [comment]
We had a private speaker recording around 10 hours of speech for our preliminary test.
